name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
publish_to: none
topics:
  - cache
  - image
  - network-image
version: 3.2.4
environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  cached_network_image_platform_interface:
    git:
      url: https://github.com/selvam920/flutter_cached_network_image.git
      ref: develop
      path: cached_network_image_platform_interface
  cached_network_image_web:
    git:
      url: https://github.com/selvam920/flutter_cached_network_image.git
      ref: develop
      path: cached_network_image_web
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  octo_image: 
    git: 
      url: https://github.com/selvam920/octo_image

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
